### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by trakout** [ggoodman/angular-drag-drop#10] opened 2016-04-02 20:34 UTC
I can't seem to get this to work in Firefox latest (OSX latest).

The following example works in Chrome & Safari but not FF. It seems to fail silently:
https://plnkr.co/edit/8fiXfQXHUE7dbvTT0TTT?p=preview

Thoughts?

**Comment by ggoodman** [comment] 2016-07-10 16:56
Is this still an issue for you @trakout?

**Comment by ggoodman** [comment] 2016-07-10 16:59
I can see that there are some major inconsistencies in behaviour on Firefox.

**Comment by trakout** [comment] 2016-07-12 12:57
@ggoodman Yep, unfortunately still an issue (within my project & the above plunkr eg, which is a quick example of how I'm using it).

Running FF 47.0.1 on on Mac OS 10.11.4.

**Comment by tefdos** [comment] 2016-08-05 14:08
You can try the solution proposed on https://stackoverflow.com/questions/19055264/why-doesnt-html5-drag-and-drop-work-in-firefox.
Adding `e.originalEvent.dataTransfer.setData('text', 'anything');` on `handleDragStart` fixed it for me on FF 48.0 OSX 10.11.1.

**Comment by trakout** [comment] 2016-08-17 01:52
@tefdos good catch, that fixes it for me. I didn't reference originalEvent -- [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart) does not seem to mention it either, so it was just `e.dataTransfer.setData('text', 'anything');`.

@ggoodman I've added the 1-liner in #13 -- [line 71](https://github.com/ggoodman/angular-drag-drop/compare/master...trakout:ff-fix?expand=1#diff-78bb95ab40f5ba0502887daff05c7786R71).

**Comment by ggoodman** [comment] 2016-08-17 12:32
Fixed in 137d301336d7d88eb52b4aa2121da54019861dce. Please use `3.0.2`.

Major bump to account for new behaviour whereby the element's `.text()` will be set as a `text` `dataTransfer` entry if no other items or files were added by user code.

**Closed as completed by ggoodman** 2016-08-17 12:32 UTC
Labels: bug

**Comment by jziggas** [comment] 2018-05-23 13:37
This is still an issue in Firefox.

**Comment by ggoodman** [comment] 2018-05-23 14:12
@jziggas I'll open if you can show me some sort of reproduction. My own use of this library isn't having any issues on latest FF.

**Comment by jziggas** [comment] 2018-05-23 14:22
I can't get https://plnkr.co/edit/8FHDWgxAhuriIC9DXptd?p=preview to work in FF.

In my own app I can seem to reliably reproduce an issue when you do a sort of double click while dragging (like click and hold, start dragging, let go, and click again while still dragging). It looks like onDragEnd is never called because the drop containers are still highlighted and you can't drag any more items. The same can be achieved in the plunkr above.

Edit: Updated the plunkr link because the first one might have had an old version of your library.

**Comment by ggoodman** [comment] 2018-05-23 14:37
AngularJS on Firefox appears to block the use of DOM elements in expressions. By default `angular-drag-drop` will set the element itself as the drag data. An easy way out is the set custom drag data using the `drag-data="scopeReference"` property.

I've modified your example to use `drag-data="'Drag Me'"` [in this fork of your plunk](https://plnkr.co/edit/uPkGvzynxJCfta4OCC0E?p=preview) and have tested this.

**Comment by jziggas** [comment] 2018-05-23 14:40
Although it wasn't in the plunkr, I do already have `drag-data=""` set in my app to move objects around.

I'll see if I can come up with a different plunkr.

**Comment by jziggas** [comment] 2018-05-23 14:42
Actually in your plunkr I can still repro the issue where dragging stops working.

**Comment by jziggas** [comment] 2018-05-23 14:45
http://recordit.co/vF1Qdu5ybT

**Comment by ggoodman** [comment] 2018-05-23 14:45
@jziggas I think you should open a new issue to track this with as much detail as possible.

**Comment by jziggas** [comment] 2018-05-23 14:46
@ggoodman NP will do.
